const LIMIT=8388608,MAX_MS=600000;
export class Recorder{
  constructor(events){this.events=events;this.stream=null;this.recorder=null;this.chunks=[];this.timer=null;this.generation=0}
  supported(){return Boolean(navigator.mediaDevices?.getUserMedia&&window.MediaRecorder)}
  chooseMime(provider){const candidates=provider==="groq"?["audio/webm;codecs=opus","audio/ogg;codecs=opus","audio/mp4"]:["audio/webm;codecs=opus","audio/ogg;codecs=opus"];return candidates.find(x=>MediaRecorder.isTypeSupported(x))||null}
  async start(provider){const generation=++this.generation;const mime=this.chooseMime(provider);if(!mime)throw new Error("This browser cannot record a format accepted by the selected provider. Upload a supported audio file instead.");this.events.state("permission");const stream=await navigator.mediaDevices.getUserMedia({audio:true});if(generation!==this.generation){stream.getTracks().forEach(t=>t.stop());return}this.stream=stream;this.chunks=[];this.recorder=new MediaRecorder(stream,{mimeType:mime});this.recorder.ondataavailable=e=>{if(e.data.size){this.chunks.push(e.data);if(this.chunks.reduce((n,b)=>n+b.size,0)>LIMIT)this.stop(true)}};this.recorder.onerror=()=>this.stop(true);stream.getTracks().forEach(t=>{t.onended=()=>this.stop(true);t.onmute=()=>this.stop(true)});this.started=performance.now();this.recorder.start(1000);this.timer=setTimeout(()=>this.stop(false),MAX_MS);this.events.state("recording")}
  stop(interrupted=false){clearTimeout(this.timer);if(this.recorder?.state==="recording"){this.recorder.onstop=()=>{const blob=new Blob(this.chunks,{type:this.recorder.mimeType});this.release();if(!blob.size||blob.size>LIMIT)this.events.error("The recording is empty or larger than 8 MiB.");else this.events.ready(blob,Math.min((performance.now()-this.started)/1000,600),interrupted)};this.recorder.stop()}else this.release()}
  cancel(){this.generation++;this.chunks=[];this.release()}
  release(){clearTimeout(this.timer);this.stream?.getTracks().forEach(t=>t.stop());this.stream=null;this.recorder=null}
}
export async function inspectUpload(file){if(!file||!file.size)throw new Error("Choose a nonempty audio file.");if(file.size>LIMIT)throw new Error("Choose audio smaller than 8 MiB.");const bytes=new Uint8Array(await file.slice(0,12).arrayBuffer());const text=String.fromCharCode(...bytes);const valid=text.startsWith("RIFF")&&text.slice(8,12)==="WAVE"||text.startsWith("ID3")||bytes[0]===255&&[251,243,242].includes(bytes[1])||text.startsWith("fLaC")||text.startsWith("OggS")||bytes[0]===0x1a&&bytes[1]===0x45&&bytes[2]===0xdf&&bytes[3]===0xa3||text.slice(4,8)==="ftyp";if(!valid)throw new Error("This file does not have a recognized supported audio container.");return new Promise(resolve=>{const audio=document.createElement("audio"),url=URL.createObjectURL(file);audio.preload="metadata";const done=value=>{URL.revokeObjectURL(url);resolve({file,duration:Number.isFinite(value)&&value>0?value:null})};audio.onloadedmetadata=()=>done(audio.duration);audio.onerror=()=>done(null);audio.src=url})}
