const make=(tag,attrs={})=>Object.assign(document.createElement(tag),attrs);
function inputFor(field,value){let input;if(field.type==="textarea")input=make("textarea",{rows:4});else if(field.type==="select"){input=make("select");input.append(make("option",{value:"",textContent:"Select one"}));field.options.forEach(o=>input.append(make("option",{value:o.value,textContent:o.label})))}else if(field.type==="boolean"){input=make("select");[["","Select one"],["true",field.true_text],["false",field.false_text]].forEach(([v,t])=>input.append(make("option",{value:v,textContent:t})))}else input=make("input",{type:field.type==="integer"?"text":field.type});input.dataset.fieldType=field.type;input.value=value===null?"":String(value);input.required=field.required;return input}
export function buildForm(container,config,onChange){container.replaceChildren();config.fields.forEach(field=>container.append(fieldGroup(field,field.default,onChange,field.id)));config.sections.forEach(section=>{const group=make("fieldset");group.dataset.section=section.id;group.append(make("legend",{textContent:section.label}),make("p",{textContent:section.help}));const rows=make("div",{className:"rows"});group.append(rows);const add=make("button",{type:"button",textContent:"Add item",className:"secondary"});add.addEventListener("click",()=>{if(rows.children.length<section.max_rows){addRow(rows,section,null,onChange);onChange()}});group.append(add);container.append(group);section.default_rows.forEach(r=>addRow(rows,section,r,onChange));});}
function fieldGroup(field,value,onChange,key){const wrap=make("div");const id=`field-${key}-${crypto.randomUUID()}`;const label=make("label",{htmlFor:id,textContent:field.label+(field.required?" *":"")});const input=inputFor(field,value);input.id=id;input.dataset.field=field.id;input.setAttribute("aria-describedby",id+"-help");const help=make("small",{id:id+"-help",textContent:field.help});input.addEventListener("input",onChange);wrap.append(label,input,help);return wrap}
function addRow(rows,section,value,onChange){const card=make("div",{className:"repeat-card"});card.dataset.row="";const title=make("strong",{textContent:`Item ${rows.children.length+1}`});card.append(title);section.row_fields.forEach(f=>card.append(fieldGroup(f,value?.[f.id]??f.default,onChange,`${section.id}-${f.id}`)));const tools=make("div",{className:"row-tools"});[["Move up",-1],["Move down",1]].forEach(([text,delta])=>{const b=make("button",{type:"button",textContent:text,className:"secondary"});b.onclick=()=>{const other=delta<0?card.previousElementSibling:card.nextElementSibling;if(other){delta<0?rows.insertBefore(card,other):rows.insertBefore(other,card);renumber(rows);onChange()}};tools.append(b)});const remove=make("button",{type:"button",textContent:"Remove",className:"secondary"});remove.onclick=()=>{const dirty=[...card.querySelectorAll("input,textarea,select")].some(x=>x.value);if(!dirty||confirm("Remove this nonempty item?")){card.remove();renumber(rows);onChange()}};tools.append(remove);card.append(tools);rows.append(card)}
function renumber(rows){[...rows.children].forEach((row,i)=>row.querySelector("strong").textContent=`Item ${i+1}`)}
function typed(input){if(input.dataset.fieldType==="integer")return input.value===""?null:/^-?\d+$/.test(input.value)?Number(input.value):input.value;if(input.dataset.fieldType==="boolean")return input.value===""?null:input.value==="true";return input.value}
export function collectValues(container,config){const fields={};config.fields.forEach(f=>{fields[f.id]=typed(container.querySelector(`[data-field="${CSS.escape(f.id)}"]`))});const sections={};config.sections.forEach(s=>{sections[s.id]=[...container.querySelector(`[data-section="${CSS.escape(s.id)}"] .rows`).children].map(row=>{const out={};s.row_fields.forEach(f=>out[f.id]=typed(row.querySelector(`[data-field="${CSS.escape(f.id)}"]`)));return out})});return{fields,sections}}
export function validateValues(config,values){const issues=[];const check=(f,v,label)=>{if(f.required&&(v===null||String(v).trim()===""))issues.push(`${label} is required.`);if((f.type==="text"||f.type==="textarea")&&String(v).length>(f.validation?.max_length??20000))issues.push(`${label} is too long.`);if(f.type==="integer"&&v!==null&&!Number.isInteger(v))issues.push(`${label} must be a whole number.`)};config.fields.forEach(f=>check(f,values.fields[f.id],f.label));config.sections.forEach(s=>{const rows=values.sections[s.id];if(rows.length<s.min_rows)issues.push(`${s.label} needs at least ${s.min_rows} item.`);rows.forEach((r,i)=>s.row_fields.forEach(f=>check(f,r[f.id],`${s.label}, item ${i+1}, ${f.label}`)))});return issues}
export function displayValue(f,v){if(v===null||v===undefined)return"";if(f.type==="select")return f.options.find(o=>o.value===v)?.label||"";if(f.type==="boolean")return v?f.true_text:f.false_text;if(f.type==="date"&&v){const[y,m,d]=v.split("-");return f.display_format==="DD/MM/YYYY"?`${d}/${m}/${y}`:f.display_format==="MM/DD/YYYY"?`${m}/${d}/${y}`:v}return String(v)}
